name: run android tests in github runner

on: push

jobs:
  run-android-mobile-tests:
    runs-on: macos-latest

    steps:
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: pull the project in to the runner
        uses: actions/checkout@v4

      - name: setup appium
        run: |
          npm install -g appium@v1.22
          appium -v
          appium &>/dev/null &

      - name: start android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis_arm64_v8a
          arch: arm64-v8a
          script: |
            adb wait-for-device
            adb shell input keyevent 82

      - name: wait for emulator to be ready
        run: |
          sleep 30
          adb devices

      - name: run appium android tests
        run: mvn clean test -Pandroid